circler/config/routes.rb
Rails.application.routes.draw do
  resources :chats
  resources :chats do
    collection do
      post :confirm
    end
  end
end

circler/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

circler/app/models/chat.rb
class Chat < ApplicationRecord
  validates :content, presence: true,
                      length: {maximum: 140}
end

circler/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

circler/app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only:[:show, :edit, :update, :destroy]
  
  def index
    @chats = Chat.all
  end
  
  def new
    if params[:back]
      @chat = Chat.new(chat_params)
    else
      @chat = Chat.new
    end
  end

  def confirm
    @chat = Chat.new(chat_params)
    render :new if @blog.invalid?
  end
  
  def create
    @chat = Chat.new(chat_params)
    if @chat.save
    redirect_to chats_path,notice:"投稿しました！"
    else
    render 'new'
    end
  end
  

  
  def show
    @chat = Chat.find(params[:id])
  end
  
  def edit
    @chat = Chat.find(params[:id])
  end
  
  def update
    @chat = Chat.find(params[:id])
    if @chat.update(chat_params)
      redirect_to chats_path, notice: "内容を編集しました" 
    else
      render 'edit'
    end
  end
  
def destroy
  @chat.destroy
  redirect_to chats_path, notice:"削除しました！"
end

  private
  
  def chat_params
    params.require(:chat).permit(:content)
  end

  def set_chat
    @chat = Chat.find(params[:id])
  end
end

circler/app/helpers/application_helper.rb
module ApplicationHelper
end

circler/app/helpers/chats_helper.rb
module ChatsHelper
  def choose_new_or_edit
    if action_name == 'new'||action_name == 'confirm' 
      confirm_chats_path
    elsif action_name == 'edit'
      chat_path
    end
  end
end

circler/app/views/chats/_form.html.erb
<%= form_with(model: @chat, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= @chat.errors.count %>件のエラーがあります。</h2>
      <ul>
          
      <% @chat.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>      
      </ul>
    </div>
  <% end %>

  <div class= "chat_content">
      <%= form.label :content %>
      <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "トップページに戻る",chats_path %>

circler/app/views/chats/confirm.html.erb
<h3>以下の内容で投稿する</h3>

<%= form_with(model: @chat, url: chats_path, local: true) do |form| %>
<%= form.hidden_field :content %>

<p>本文:<%= @chat.content %></p>
<p><%= form.submit "登録する" %></p>
<% end %>

<%= form_with(model: @chat, url:new_chat_path, local: true, methoed: 'get') do |form| %>
<%= form.hidden_field :content %>
<%= form.submit "戻る", name: 'back' %>
<% end %>

circler/app/views/chats/edit.html.erb
<h2>投稿内容を編集する</h2>

<%= render 'form' %>

circler/app/views/chats/index.html.erb
<!DOCTYPE html>
<html lasng="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Achieve</title>
    <link rel="stylesheet" href="vendors/css/normalize.css">
    <link rel="stylesheet" href="vendors/css/task.css">
</head>

<body>
    <h1>circler mainページ</h1>
    <p><%= notice %></p>

    <table>
      <tr>
        <th>投稿内容</th>
      </tr>

      <% @chats.each do |chat| %>
        <tr>
          <td><%= chat.content %></td>
          <td><%= link_to '詳細を確認する', chat_path(chat.id) %></td>
          <td><%= link_to "投稿内容を編集する", edit_chat_path(chat.id), data: { confirm: "編集していいですか？"}  %></td>
          <td><%= link_to "投稿を削除する", chat_path(chat.id), method: :delete , data: { confirm: "本当に削除していいですか? "} %></td>
         </tr>
      <% end %>
    </table>

    <%= link_to '新しく投稿する', new_chat_path %>
  
    <footer>
    <p>circler運営部</p>
    <p>© 2015-2018 Copyright circle of circler</p>
  </footer>
</body>
</html>

circler/app/views/chats/new.html.erb
<h2>新規投稿する</h2>

<%= render 'form' %>

circler/app/views/chats/show.html.erb
<h1>投稿詳細画面</h1>
<p>投稿内容：<%= @chat.content %></p>

circler/app/views/chats/view.html.erb
<h2>新規投稿する</h2>

<%= render 'form' %>

circler/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Circler</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>